"""
Data Loader — reads and validates the filled-in Excel IRO template.

Expected sheet: 'IRO_Eingabe'
Expected columns (by header name):
    IRO-ID, ESRS-Thema, IRO-Typ, Beschreibung,
    Ausmaß (1–5), Reichweite (1–5), Behebbarkeit (1–5),
    Eintritts- wahrsch. (1–5), Fin. Auswirkung (1–5), Zeithorizont
"""

import json
import os
from openpyxl import load_workbook
from src.exceptions import InvalidScoreError, MissingIROError

SHEET_NAME = "IRO_Eingabe"
SCORE_FIELDS = ["magnitude", "scope", "irremediability", "likelihood", "fin_magnitude"]
VALID_HORIZONS = {"short", "medium", "long"}

CONFIG_PATH = os.path.join(os.path.dirname(__file__), "..", "config", "esrs_topics.json")

# Mapping from Excel column header (partial match) to internal field name
COLUMN_MAP = {
    "IRO-ID": "iro_id",
    "ESRS-Thema": "esrs_topic",
    "IRO-Typ": "iro_type",
    "Beschreibung": "description",
    "Ausmaß": "magnitude",
    "Reichweite": "scope",
    "Behebbarkeit": "irremediability",
    "Eintritts": "likelihood",
    "Fin. Auswirkung": "fin_magnitude",
    "Zeithorizont": "time_horizon",
}


def _load_expected_iro_ids() -> list[str]:
    """Return all expected IRO IDs from config."""
    with open(CONFIG_PATH, encoding="utf-8") as f:
        config = json.load(f)
    ids = []
    for topic in config["topics"]:
        for iro in topic["iros"]:
            ids.append(iro["iro_id"])
    return ids


def _resolve_headers(ws) -> dict[str, int]:
    """
    Read header row and map internal field names to column indices.
    Returns {field_name: col_index (1-based)}.
    """
    header_row = [cell.value for cell in ws[1]]
    resolved = {}
    for col_idx, header in enumerate(header_row, start=1):
        if header is None:
            continue
        # Normalize multiline headers (strip newlines/extra spaces)
        header_clean = " ".join(str(header).split())
        for key, field in COLUMN_MAP.items():
            if key in header_clean:
                resolved[field] = col_idx
                break
    return resolved


def load_iros(input_path: str) -> list[dict]:
    """
    Read and validate the filled IRO input template.

    Args:
        input_path: Path to the filled .xlsx file.

    Returns:
        List of dicts, one per IRO, with all raw input fields.

    Raises:
        FileNotFoundError: If the file does not exist.
        ValueError: If the expected sheet is not found.
        MissingIROError: If an expected IRO row is absent.
        InvalidScoreError: If a score is outside 1–5 or horizon is invalid.
    """
    if not os.path.exists(input_path):
        raise FileNotFoundError(f"Input file not found: '{input_path}'")

    try:
        wb = load_workbook(input_path, data_only=True)
    except Exception as e:
        raise ValueError(f"Could not open Excel file '{input_path}': {e}") from e

    if SHEET_NAME not in wb.sheetnames:
        raise ValueError(
            f"Sheet '{SHEET_NAME}' not found in '{input_path}'. "
            f"Available sheets: {wb.sheetnames}"
        )

    ws = wb[SHEET_NAME]
    col_map = _resolve_headers(ws)

    required_fields = list(COLUMN_MAP.values())
    missing_cols = [f for f in required_fields if f not in col_map]
    if missing_cols:
        raise ValueError(
            f"Missing columns in sheet '{SHEET_NAME}': {missing_cols}. "
            f"Ensure the template was generated by this tool."
        )

    # Read all data rows
    rows_by_id: dict[str, dict] = {}
    for row in ws.iter_rows(min_row=2, values_only=True):
        iro_id = row[col_map["iro_id"] - 1]
        if not iro_id:
            continue
        iro_id = str(iro_id).strip()
        rows_by_id[iro_id] = {
            field: row[col_idx - 1]
            for field, col_idx in col_map.items()
        }

    expected_ids = _load_expected_iro_ids()
    iros = []

    for iro_id in expected_ids:
        if iro_id not in rows_by_id:
            raise MissingIROError(iro_id)

        raw = rows_by_id[iro_id]
        validated = {"iro_id": iro_id}

        # Copy text fields
        validated["esrs_topic"] = str(raw["esrs_topic"]).strip()
        validated["iro_type"] = str(raw["iro_type"]).strip()
        validated["description"] = str(raw["description"]).strip()

        # Validate score fields
        for field in SCORE_FIELDS:
            value = raw.get(field)
            try:
                int_val = int(value)
            except (TypeError, ValueError):
                raise InvalidScoreError(iro_id, field, value)
            if not (1 <= int_val <= 5):
                raise InvalidScoreError(iro_id, field, int_val)
            validated[field] = int_val

        # Validate time_horizon
        horizon = raw.get("time_horizon")
        if horizon is None or str(horizon).strip().lower() not in VALID_HORIZONS:
            raise InvalidScoreError(iro_id, "time_horizon", horizon)
        validated["time_horizon"] = str(horizon).strip().lower()

        iros.append(validated)

    return iros
